apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/kh0inv/k8s-deployment.git'
        revision: HEAD
        files:
          - path: "deployments/**/.argocd-config.json"
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: '{{ default "default" .project }}'
      source:
        repoURL: 'https://github.com/kh0inv/k8s-deployment.git'
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ default .path.basename .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  templatePatch: |
    {{- if eq (default "directory" .appType) "helm" }}
    spec:
      source:
        helm:
          valueFiles:
            - '{{ default "values.yaml" .valuesFile }}'
    {{- end }}
